import { describe, expect, it } from "vitest";
import { classifyTaskIntent, expandedQueryTerms } from "../src/retrieval.js";
import { promptModeForTask } from "../src/retrieval/intent.js";

describe("retrieval prompt intent", () => {
  it.each([
    "Session start: identify project focus, current changes, workflows, and next Codexa call",
    "Review the debugging changes in src/util.ts",
    "Explain the fixed bug in src/util.ts",
    "Inspect hardened permissions in src/auth.ts",
    "Identify created files",
    "Fixed bug in src/util.ts",
    "Hardened permissions in src/auth.ts",
    "Restricted access in src/auth.ts",
    "Synchronized cache state in src/cache.ts",
    "Created src/new.ts",
    "Create a report of API callers in src/api.ts",
    "Review src/api.ts, then debug the auth failure",
    "Make sense of the API in src/api.ts",
    "Build an understanding of the API in src/api.ts",
    "Write up a summary of the API",
    "Create a test plan for the API",
    "Write a checklist for the API change",
    "Build a TODO list for auth",
    "Create a proposal for the schema change",
    "Create a security review of src/api.ts",
    "Write an API analysis of src/api.ts",
    "Create an API migration plan for src/api.ts",
    "Write a security assessment of src/api.ts",
    "Create an implementation plan for src/api.ts",
    "Write a dependency map of src/api.ts",
    "Explain the bug and fix options in src/api.ts",
    "Compare fix and update strategies for src/api.ts",
    "Building an understanding of API security",
    "Writing an API analysis",
    "Creating a security review",
    "Create a plan to fix src/api.ts",
    "Write a checklist to migrate src/api.ts",
    "Generate a report detailing API changes in src/api.ts",
    "Write a summary describing the API update in src/api.ts",
    "Create a security report with fixes for src/util.ts",
    "Create a plan with options to fix src/util.ts",
    "Write a migration plan covering changes to src/util.ts",
    "Create a review and recommendations for src/util.ts",
    "Write a report that describes the API in src/util.ts",
    "Generate a report including security recommendations for src/util.ts",
    "Does src/util.ts need fixing?",
    "Does src/util.ts need a fix?",
    "Check whether src/util.ts needs fixing",
    "Assess whether src/util.ts needs fixing",
    "Determine whether src/util.ts needs fixing",
    "Verify whether src/util.ts needs fixing",
    "Tell me whether src/util.ts needs fixing",
    "Explain how to fix and update src/util.ts",
    "Show the fix and update history for src/util.ts",
    "Create a report in Markdown detailing API callers",
    "Write a summary in Markdown describing API changes",
    "Generate a report in JSON covering API changes",
    "Create a dependency map from src/api.ts to src/util.ts",
    "Try to write a summary of src/api.ts",
    "Start writing a report about src/api.ts",
    "Use the index to build a dependency map of src/api.ts",
    "Making sense of the API",
    "Building a dependency map",
    "Writing up a security review",
    "Patch review for API changes in src/api.ts",
    "Change review for the API in src/api.ts"
  ])("keeps %s read-only", (task) => {
    expect(promptModeForTask(task)).toBe("orientation");
    expect(classifyTaskIntent(task)).not.toContain("implementation");
  });

  it.each([
    "Fix src/util.ts",
    "Harden src/auth.ts",
    "Restrict src/auth.ts",
    "Synchronize src/cache.ts",
    "Create src/new.ts",
    "Please fix src/util.ts",
    "Review src/a.ts, then fix src/b.ts",
    "Need to harden API permissions in src/api.ts",
    "Task: Harden API permissions in src/api.ts",
    "Context first. Harden API permissions in src/api.ts",
    "Make src/api.ts enforce permissions",
    "Create a report, then fix src/api.ts",
    "Write an analysis and harden auth",
    "Resolve the API bug in src/api.ts",
    "Apply the security fix in src/api.ts",
    "We should fix API permissions in src/api.ts",
    "Please can you fix API permissions in src/api.ts",
    "Finish the API fix in src/api.ts",
    "Complete the auth implementation in src/api.ts",
    "Continue fixing auth in src/api.ts",
    "Address the security findings in src/api.ts",
    "Ensure API permissions in src/api.ts",
    "Improve API permissions in src/api.ts",
    "Upgrade API behavior in src/api.ts",
    "Correct API permissions in src/api.ts",
    "Set API permissions in src/api.ts",
    "Extract API permissions from src/api.ts",
    "Patch API auth in src/api.ts",
    "Patch src/api.ts",
    "Change the API in src/api.ts",
    "Adjust API auth in src/api.ts",
    "Revise API auth in src/api.ts",
    "Enable API auth in src/api.ts",
    "Review src/api.ts before fixing authentication",
    "Create a report: fix src/api.ts",
    "Review src/api.ts: implement the fix",
    "Inspect auth:\nfix the bug",
    "I need API auth fixed in src/api.ts",
    "API auth should be fixed in src/api.ts",
    "The API auth needs fixing in src/api.ts",
    "Can we fix API auth in src/api.ts?",
    "Please help fix API auth in src/api.ts",
    "Help me fix API auth in src/api.ts",
    "I would like to fix API auth in src/api.ts",
    "I need help fixing API auth in src/api.ts",
    "We are fixing API auth in src/api.ts",
    "Would you mind fixing src/util.ts?",
    "I'd like you to fix src/util.ts",
    "Need src/util.ts fixed",
    "I want src/util.ts fixed",
    "We need src/util.ts fixed",
    "Please proceed to fix src/util.ts",
    "Proceed with fixing src/util.ts",
    "Format src/util.ts",
    "Reformat src/util.ts",
    "Clean up src/util.ts",
    "Document the API in src/api.ts",
    "Annotate src/api.ts",
    "Bump the version in package.json",
    "Pin react in package.json",
    "Downgrade react in package.json",
    "Sort imports in src/util.ts",
    "Reorder imports in src/util.ts",
    "Introduce a helper in src/util.ts",
    "Deduplicate src/util.ts",
    "Consolidate helpers in src/util.ts",
    "Merge the helpers in src/util.ts",
    "Edit src/util.ts",
    "Rewrite src/util.ts",
    "Convert src/util.ts to ESM",
    "Relocate src/util.ts to src/lib/util.ts",
    "Transform src/util.ts",
    "src/util.ts should be edited",
    "src/util.ts should be rewritten",
    "src/util.ts should be converted",
    "src/util.ts should be relocated",
    "src/util.ts should be transformed",
    "Use src/api.ts to fix src/util.ts",
    "Try to fix src/util.ts",
    "Attempt to fix src/util.ts",
    "Start fixing src/util.ts",
    "Begin fixing src/util.ts",
    "Keep fixing src/util.ts",
    "Go ahead with fixing src/util.ts",
    "I need help with fixing src/util.ts",
    "The task is to fix src/util.ts",
    "Your goal is to fix src/util.ts",
    "- Fix src/util.ts",
    "- [ ] Fix src/util.ts",
    "Write a report to docs/report.md",
    "Create a report in docs/report.md",
    "Create a report and save it to docs/report.md",
    "Create a report of src/api.ts at docs/report.md",
    "Write a summary of src/api.ts to docs/summary.md",
    "Save the report to docs/report.md",
    "Create plan.ts",
    "Write report.ts",
    "Build map.ts",
    "Create summary.ts",
    "Write checklist.ts",
    "Create graph.ts",
    "Create review.ts",
    "I need a fix for src/util.ts",
    "src/util.ts needs a fix",
    "Auth needs a fix in src/api.ts",
    "The endpoint requires a change in src/api.ts"
  ])("keeps %s edit-directed", (task) => {
    expect(promptModeForTask(task)).toBe("edit");
    expect(classifyTaskIntent(task)).toContain("implementation");
  });

  it("keeps retrieval synonyms out of topical and edit authority", () => {
    expect(expandedQueryTerms("src/query/graph.ts")).toContain("workflow");
    expect(classifyTaskIntent("Inspect src/query/graph.ts")).not.toContain("workflow");
    expect(classifyTaskIntent("Explain the fixed bug")).toContain("debugging");
    expect(classifyTaskIntent("Explain the fixed bug")).not.toContain("implementation");
  });

  it("lets structured material change types override prose orientation", () => {
    expect(promptModeForTask("Inspect src/api.ts", "api")).toBe("edit");
    expect(promptModeForTask("Inspect src/api.ts", "rename")).toBe("edit");
    expect(promptModeForTask("Inspect src/api.ts", "delete")).toBe("edit");
    expect(promptModeForTask("Inspect src/api.ts", "behavior")).toBe("orientation");
  });
});
