import { lstat, mkdir, readFile, realpath, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const CI_WORKFLOW_RELATIVE_PATH = ".github/workflows/codexa-review.yml";
const CI_WORKFLOW_START = "# >>> codexa managed workflow";
const CI_WORKFLOW_END = "# <<< codexa managed workflow";

export async function assertCiWorkflowWritable(repoRoot: string): Promise<void> {
  const githubDir = path.join(repoRoot, ".github");
  const workflowsDir = path.join(githubDir, "workflows");
  await assertExistingDirectoryIsNotSymlink(githubDir);
  await assertExistingDirectoryIsNotSymlink(workflowsDir);
  const workflowPath = path.join(repoRoot, CI_WORKFLOW_RELATIVE_PATH);
  try {
    const stat = await lstat(workflowPath);
    if (!stat.isFile() || stat.isSymbolicLink()) {
      throw new Error(`Cannot write ${workflowPath}: target is not a regular non-symlink file`);
    }
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") return;
    throw error;
  }
  const existing = await readFile(workflowPath, "utf8");
  const starts = existing.split(CI_WORKFLOW_START).length - 1;
  const ends = existing.split(CI_WORKFLOW_END).length - 1;
  const trimmed = existing.trim();
  if (starts !== 1 || ends !== 1 || !trimmed.startsWith(CI_WORKFLOW_START) || !trimmed.endsWith(CI_WORKFLOW_END)) {
    throw new Error(`Cannot write ${workflowPath}: existing workflow is not owned by Codexa; remove or rename it before using --ci`);
  }
}

export async function writeCiWorkflow(repoRoot: string, version: string): Promise<string> {
  if (!/^[0-9A-Za-z][0-9A-Za-z.+-]{0,63}$/u.test(version)) throw new Error("Cannot initialize CI: Codexa version is invalid");
  await assertCiWorkflowWritable(repoRoot);
  const workflowPath = path.join(repoRoot, CI_WORKFLOW_RELATIVE_PATH);
  const workflowDir = path.dirname(workflowPath);
  await mkdir(workflowDir, { recursive: true });
  const resolvedRepo = await realpath(repoRoot);
  const resolvedDir = await realpath(workflowDir);
  if (resolvedDir !== resolvedRepo && !resolvedDir.startsWith(`${resolvedRepo}${path.sep}`)) {
    throw new Error(`Cannot write ${workflowPath}: workflow directory resolves outside the repository`);
  }
  const temporaryPath = `${workflowPath}.${process.pid}.${Date.now()}.tmp`;
  try {
    await writeFile(temporaryPath, renderCiWorkflow(version), { encoding: "utf8", flag: "wx" });
    await rename(temporaryPath, workflowPath);
  } catch (error) {
    await rm(temporaryPath, { force: true }).catch(() => undefined);
    throw error;
  }
  return workflowPath;
}

function renderCiWorkflow(version: string): string {
  return [
    CI_WORKFLOW_START,
    "# Generated by codexa init --ci. Re-run that command to update this file.",
    "name: Codexa Review",
    "",
    "on:",
    "  pull_request:",
    "",
    "permissions:",
    "  contents: read",
    "",
    "jobs:",
    "  review:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - name: Check out pull request head",
    "        uses: actions/checkout@v6",
    "        with:",
    "          fetch-depth: 0",
    "          persist-credentials: false",
    "          ref: ${{ github.event.pull_request.head.sha }}",
    "      - name: Review committed change",
    `        uses: mirnoorata/codexa@v${version}`,
    "        with:",
    "          base: ${{ github.event.pull_request.base.sha }}",
    "          head: ${{ github.event.pull_request.head.sha }}",
    "          mode: observe",
    CI_WORKFLOW_END,
    ""
  ].join("\n");
}

async function assertExistingDirectoryIsNotSymlink(directory: string): Promise<void> {
  try {
    const stat = await lstat(directory);
    if (!stat.isDirectory() || stat.isSymbolicLink()) {
      throw new Error(`Cannot initialize CI: ${directory} is not a regular directory`);
    }
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") return;
    throw error;
  }
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}
